version: '2'
services:
  api_movies:
    build:
      context: ./movies-service
      dockerfile: Dockerfile
    ports:
      - 8088:8080
    links:
      - "db"
    volumes:
      - ./movies-service:/code
    working_dir: /code/src
    command: "apistar run --host 0.0.0.0"
    environment:
      - DBUSER=mongo
      - DBPWD=mongo
      - DBHOST=db
      - DBPORT=27017
      - DBNAME=movies
  db:
    image: mongo
    ports:
     - "27017:27017"
    volumes:
     - data-mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    restart: always

volumes:
  data-mongo: